apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: elasticsearch
spec:
 replicas: 1
 template:
    metadata:
      creationTimestamp: null
      labels:
        name: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: elasticsearch
        name: elasticsearch
        ports:
        - containerPort: 9200
        
      restartPolicy: Always
